apiVersion: v1
metadata:
    name: sonarr-exporter-secret
    namespace: monitoring
kind: Secret
stringData:
    APIKEY: ENC[AES256_GCM,data:0fxl/z2TTj42KzR9M8Du0qc0uW9trkiHnFnfMq57HZQ=,iv:2ZyVNUevKFfvn/3gk2t+9lQezLLzKtLK37TpPiNrUKY=,tag:RF0lH4dhlBLjokRN4zEUfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSjNyRmE1ZjhnWG5OM1BQ
            YkIwTzBHdWdyQVZiMlc5VFh5Ny9JUUlVRHlNCms1UFBDa3QzanI0YVI3SlJVQWw0
            a0xUckR5eGpIdm5rR2tQUVdDQkRZWFUKLS0tIDFiWDdSQWZvRitMRi9xcmhpWkdp
            N0NUbzZSRDFLYnpLK0pjMXVFM3VramMKreAVvInlEAnc/dLWfv30EAGEqNIcpEny
            9vpq2VGHql1m3K92yAsUFA6ij4UpsGA7VgckYH/zcg8SgdeokOuvJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T21:31:51Z"
    mac: ENC[AES256_GCM,data:ytXekfdNZH4ydlSmX9b5eEDkN2FksnHt11UijHg4XVkP5sC5P+qe7E7KwhPZlVnO8VyLGnzlz+p4DFU7hVaPBJDfaX3GYrvqdrfU1KsDqLnE0z2ybpvKHf4WQ5fDSzhmNq6U9XG/7p1c5PWnnpF32TWEijz+zE8UeETE5mTJjDs=,iv:ojE+gvsN58e3jDSnsQM0bc3KDMdishe5unXMMi6XxTg=,tag:+STACDxJVWIC/CXJIQt0xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
