---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: loki
      version: 4.8.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    loki:
      structuredConfig:
        auth_enabled: false

        server:
          log_level: info
          http_listen_port: 3100
          grpc_listen_port: 9095

        memberlist:
          join_members: ["loki-memberlist"]

        limits_config:
          retention_period: 14d
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          max_cache_freshness_per_query: 10m
          split_queries_by_interval: 15m
          ingestion_rate_mb: 16
          ingestion_burst_size_mb: 32
          shard_streams:
            enabled: true

        schema_config:
          configs:
            - from: "2021-08-01"
              store: boltdb-shipper
              object_store: s3
              schema: v11
              index:
                prefix: loki_index_
                period: 24h

        common:
          path_prefix: /var/loki
          replication_factor: 3
          storage:
            s3:
              # s3: null
              insecure: true
              s3forcepathstyle: true
              # endpoint: "192.168.183.210:9000"
              bucketnames: loki
              # access_key_id: "${LOKI_MINIO_ACCESS_KEY}"
              # secret_access_key: "${LOKI_MINIO_SECRET_KEY}"
          ring:
            kvstore:
              store: memberlist

        ruler:
          enable_api: true
          enable_alertmanager_v2: true
          alertmanager_url: http://kube-prometheus-stack-alertmanager:9093
          storage:
            type: local
            local:
              directory: /rules
          rule_path: /tmp/scratch
          ring:
            kvstore:
              store: memberlist

        distributor:
          ring:
            kvstore:
              store: memberlist

        compactor:
          working_directory: /var/loki/boltdb-shipper-compactor
          shared_store: s3
          compaction_interval: 10m
          retention_enabled: true
          retention_delete_delay: 2h
          retention_delete_worker_count: 150

        ingester:
          max_chunk_age: 1h
          lifecycler:
            ring:
              kvstore:
                store: memberlist

        analytics:
          reporting_enabled: false

    gateway:
      enabled: true
      replicas: 2
      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "text-box-search"
          hajimari.io/appName: "Loki"
        hosts:
          - host: &host "loki.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
        affinity: |
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: NotIn
                  values:
                  - arm64

    write:
      replicas: 3
      persistence:
        size: 10Gi
        storageClass: longhorn
      affinity: |
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: NotIn
                values:
                - arm64

    read:
      persistence:
        storageClass: local-path
      extraVolumeMounts:
        - name: rules
          mountPath: /rules
      extraVolumes:
        - name: rules
          emptyDir: {}
      affinity: |
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: NotIn
                values:
                - arm64

    backend:
      replicas: 3
      extraVolumeMounts:
        - name: rules
          mountPath: /rules
        - name: scratch
          mountPath: /tmp/scratch
      extraVolumes:
        - name: rules
          emptyDir: {}
        - name: scratch
          emptyDir: {}
      persistence:
        size: 10Gi
        storageClass: longhorn
      affinity: |
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: NotIn
                values:
                - arm64

    monitoring:
      dashboards:
        enabled: false
        annotations:
          kustomize.toolkit.fluxcd.io/substitute: disabled
        labels:
          grafana_dashboard: 'true'
      rules:
        enabled: true
      serviceMonitor:
        enabled: false
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
        lokiCanary:
          enabled: false
    test:
      enabled: false

    storage_config:
      aws:
        bucketnames: loki
        endpoint: "http://minio.storage.svc.cluster.local:9000"
        access_key_id: "${SECRET_MINIO_USERNAME}"
        secret_access_key: "${SECRET_MINIO_PASSWORD}"
