---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: loki
      version: 4.10.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    loki:

      storage:
        s3:
          s3: null
          endpoint: http://minio.storage.svc.cluster.local:9000
          region: null
          secretAccessKey: ${LOKI_MINIO_SECRET_KEY}
          accessKeyId: ${LOKI_MINIO_ACCESS_KEY}
          s3ForcePathStyle: true
          insecure: true

      structuredConfig:
        auth_enabled: false
        limits_config:
          retention_period: 14d
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          max_cache_freshness_per_query: 10m
          split_queries_by_interval: 15m
          ingestion_rate_mb: 16
          ingestion_burst_size_mb: 32
          shard_streams:
            enabled: true

        server:
          log_level: info
          http_listen_port: 3100
          grpc_listen_port: 9095

        memberlist:
          join_members: ["loki-memberlist"]

        schema_config:
          configs:
            - from: "2021-08-01"
              store: boltdb-shipper
              object_store: s3
              schema: v11
              index:
                prefix: loki_index_
                period: 24h

        storage_config:
          boltdb_shipper:
            resync_interval: 5s
            cache_ttl: 168h
            shared_store: s3

        common:
          path_prefix: /var/loki
          replication_factor: 1
          ring:
            kvstore:
              store: memberlist

        ruler:
          enable_api: true
          enable_alertmanager_v2: true
          alertmanager_url: http://kube-prometheus-stack-alertmanager:9093
          storage:
            type: local
            local:
              directory: /rules
          rule_path: /tmp/scratch
          ring:
            kvstore:
              store: memberlist

        distributor:
          ring:
            kvstore:
              store: memberlist

        compactor:
          working_directory: /var/loki/boltdb-shipper-compactor
          shared_store: s3
          compaction_interval: 10m
          retention_enabled: true
          retention_delete_delay: 2h
          retention_delete_worker_count: 150

        ingester:
          max_chunk_age: 1h
          lifecycler:
            ring:
              kvstore:
                store: memberlist

        analytics:
          reporting_enabled: false

    gateway:
      enabled: true
      replicas: 2
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hajimari.io/enable: "false"
        hosts:
          - host: &host "loki-gateway.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    write:
      replicas: 1
      persistence:
        size: 10Gi
        storageClass: longhorn
      nodeSelector:
        kubernetes.io/arch: amd64

    read:
      replicas: 1
      persistence:
        storageClass: longhorn
      extraVolumeMounts:
        - name: rules
          mountPath: /rules
      extraVolumes:
        - name: rules
          emptyDir: {}
      nodeSelector:
        kubernetes.io/arch: amd64

    backend:
      replicas: 3
      extraVolumeMounts:
        - name: rules
          mountPath: /rules
        - name: scratch
          mountPath: /tmp/scratch
      extraVolumes:
        - name: rules
          emptyDir: {}
        - name: scratch
          emptyDir: {}
      persistence:
        size: 10Gi
        storageClass: longhorn
      nodeSelector:
        kubernetes.io/arch: amd64

    monitoring:
      dashboards:
        enabled: true
      rules:
        enabled: false
      serviceMonitor:
        enabled: true
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
        lokiCanary:
          enabled: false
          nodeSelector:
            kubernetes.io/arch: amd64
    test:
      enabled: false
