---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mosquitto
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  targetNamespace: home
  path: ./kubernetes/apps/home/mosquitto/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  timeout: 5m
