---
# yaml-language-server: $schema=https://kubernetes-schemas.18b.haus/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    groupBy: ["alertname", "job"]
    groupInterval: 10m
    groupWait: 1m
    receiver: "null"
    repeatInterval: 12h
    routes:
      - receiver: "null"
        groupInterval: 5m
        groupWait: 0s
        matchers:
          - name: alertname
            value: Watchdog
            matchType: =
        repeatInterval: 5m
      - receiver: "null"
        matchers:
          - name: alertname
            value: InfoInhibitor
            matchType: =
  inhibitRules:
    - equal: ["alertname", "namespace"]
      sourceMatch:
        - name: severity
          value: critical
          matchType: =
      targetMatch:
        - name: severity
          value: warning
          matchType: =
  receivers:
    - name: "null"
