---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    groupBy: ["alertname", "job"]
    groupInterval: 10m
    groupWait: 1m
    receiver: "null"
    repeatInterval: 12h
    routes:
      - receiver: "null"
        matchers: [{name: alertname, value: InfoInhibitor, matchType: =}]
      - receiver: heartbeat
        groupInterval: 15s
        groupWait: 0s
        repeatInterval: 5m
        matchers: [{name: alertname, value: Watchdog, matchType: =}]
  inhibitRules:
    - equal: ["alertname", "namespace"]
      sourceMatch:
        - name: severity
          value: critical
          matchType: =
      targetMatch:
        - name: severity
          value: warning
          matchType: =
  receivers:
    - name: "null"
