---
# yaml-language-server: $schema=https://crd.movishell.pl/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app recyclarr
  namespace: flux-system
spec:
  targetNamespace: media
  path: ./kubernetes/apps/media/recyclarr/app
  prune: false # revert
  dependsOn:
    - name: longhorn
    - name: volsync
    - name: external-secrets
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 1Gi
