---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

set: [pipefail]
shopt: [globstar]


vars:
  # Directories
  KUBERNETES_DIR: '{{.ROOT_DIR}}/kubernetes'
  # Files
  SOPS_CONFIG_FILE: '{{.ROOT_DIR}}/.sops.yaml'

env:
  KUBECONFIG: '{{.ROOT_DIR}}/kubeconfig'
  SOPS_AGE_KEY_FILE: '{{.ROOT_DIR}}/age.key'

includes:
  k: .taskfiles/Kubernetes
  f: .taskfiles/Flux
  talos: .taskfiles/Talos
  sops: .taskfiles/Sops
  workstation: .taskfiles/Workstation
  es: .taskfiles/ExternalSecrets
  v: .taskfiles/Volsync
  user:
    taskfile: .taskfiles/User
    optional: true

tasks:

  default: task --list
