apiVersion: v1
metadata:
    name: home-assistant-code-server-secret
    namespace: home
kind: Secret
stringData:
    id_rsa: ENC[AES256_GCM,data:KmYkDP4/ULu9wzhrYq8NMYqR3kBXQpEKDcF/1SJd0RmkiOUd5sAT4TK5UCYsbNxYJM5I4eAZ1CzhjV2obyqlL6ePku9anpNKvOI75dIaqtWK0oxMmKKklidYcD8ceJ9Wwy4sSAlq9o8GlqgQ8Z2PN+ANwhC5q6NpGpheF1H1p5JFp12ZjcCoHs8BmbJrUFiMvTGHdB2Scv4SCQRNya0aHeZKYNKO/7a7gis7v276qkt0GhaW1/7uBIcCdeR8cUXkbn2wzLztSRrbSiyZm8i21ZZPnpPJG6nsFaaAr+ubOFz1pATRxejz++D4VCm9TXRfgUnykug2fFm5jMg8MZIj7jMXbTeO8kx8D03WAs8gD+CwOBBEy1vO00yAinsW4kewrUrt34fpQXO0IYigO2Oa/H8r5/87IpTEmjOrJf5ufiqlPD6nQXWgoQkNdL1Zo+l6tmBUFaqhYBg7Im33BxPWxzPsH5wE8YVGszkPfQJfEvPnx34TOb5uKqX9eDx7p1Tmx/Y4,iv:h1gRk42YBEjg74YzvUCisN+pi6YfPGTiJf1SL6NVcYM=,tag:JzWD/m8h9n8gKJaWwv/YhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMDFHY0pTY1ZxTGY4MTRZ
            VFhYSkxCT21aejJCWmx1Z3o2OEVWb3ZEeHlVCjVBRVArWFQvUjVUQ2JicDZWNjI1
            QW9ia3JqRk9tSGpDZUVvMXRSZDMvQ1UKLS0tIC9LZ3o3NTZQSVBtZGo1azJ1YjRu
            RXdSM0ZDUWs4ZzQvbWxsbmEvcjUyU28KCm8XE7NS99Tx5A6oyCqBslG9+diGIgc/
            solPCJ45V4Is0Ab6ZQojfEprK8tPha1/zq0ijLY1S9LwlgiCmiR/EA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-12T17:41:46Z"
    mac: ENC[AES256_GCM,data:N9J8mMcBMcaTFrDhpBPyXQfA68mTkL6MY7J/LHWlLTmLPc+lF3f5p+WsunzoTK7SdBVVBIemHAVKAwjrucBjUSQ8KPJPEe0bFJimZ3huNZ3yMjLK4M+gWTxRFQJoQBBmKooiR0UCC7IpijVHmFAdE/H3n3LbG2DIhO5F45GXcT4=,iv:eYUTtgld2v1P73wrs5BYWmCd6dzPtfwHsibmzxLERg0=,tag:1vDoxcOe9J9QuGg+iImaBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
