---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: hass-homekit-static
  namespace: home
spec:
  config: '{
      "cniVersion": "1.0.0",
      "type": "macvlan",
      "master": "eth0.10",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
           {
             "address": "192.168.183.249/24"
           }
         ]
      }
    }'
