---
# yaml-language-server: $schema=https://raw.githubusercontent.com/JJGadgets/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app mosquitto
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: public.ecr.aws/docker/library/eclipse-mosquitto
      tag: 2.0.15
    global:
      nameOverride: *app

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: $MQTT_SVC_ADDRESS
        annotations:
          coredns.io/hostname: "mqtt.${SECRET_DOMAIN}"
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883
    # configMaps:
    #   config:
    #     enabled: true
    #     data:
    #       mosquitto.conf: |
    #         listener 1883
    #         allow_anonymous true
    #         persistence true
    #         persistence_location /mosquitto/data
    #         connection_messages false
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    persistence:
      data:
        enabled: true
        existingClaim: mosquitto-config-v1
      configinc:
        enabled: true
        type: custom
        volumeSpec:
          secret:
            secretName: mosquitto
    resources:
      requests:
        cpu: 15m
        memory: 105Mi
      limits:
        memory: 105Mi
