---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: &app cloudflare-ddns
  namespace: default
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          containers:
            - name: *app
              image: ghcr.io/onedr0p/kubernetes-kubectl:1.26.0@sha256:0e4be5e6ba3dbb0f12896796da78988136460bb6f027d79e51300a19a021c92a
              envFrom:
                - secretRef:
                    name: *app
              command:
                - "/bin/bash"
                - &scriptPath "/app/cloudflare-ddns.sh"
              volumeMounts:
                - name: *app
                  mountPath: *scriptPath
                  subPath: &scriptName cloudflare-ddns.sh
                  readOnly: true
          volumes:
            - name: *app
              projected:
                defaultMode: 0775
                sources:
                  - configMap:
                      name: *app
                      items:
                        - key: *scriptName
                          path: *scriptName
