---
# (string) Timezone for the servers
timezone: "Europe/London"

# (list) Additional ssh public keys to add to the nodes
# ssh_authorized_keys:

# also want intel-gpu-tools at some point

packages:
  - hdparm
  - htop
  - ipvsadm
  - lm-sensors
  - nano
  - nvme-cli
  - socat
