---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: ha
spec:
  image: ghcr.io/homeassistant-ai/ha-mcp:7.9.0
  transport: stdio
  groupRef:
    name: mcp-tools
  env:
    - name: HOMEASSISTANT_URL
      value: http://home-assistant.home.svc.cluster.local:8123
  secrets:
    - name: ha-mcp
      key: token
      targetEnvName: HOMEASSISTANT_TOKEN
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          resources:
            limits:
              cpu: "500m"
            requests:
              cpu: "10m"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
  resources:
    limits:
      cpu: 200m
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 100Mi
