---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data-v2
  namespace: services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
