---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vrising-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vrising-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # APIKEY: "{{ .SABNZBD_API_KEY }}"
  dataFrom:
    - extract:
        key: vrising