---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &name vrising
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      vrising:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            replicas: 0
            nameOverride: *name
            image:
              repository: trueosiris/vrising
              tag: "2.1"
              pullPolicy: IfNotPresent

            resources:
              requests:
                memory: 3Gi
                cpu: 1
              limits:
                memory: 10Gi

            env:
              TZ: ${TIMEZONE}
              GAMEPORT: &server 9876
              QUERYPORT: &query 9877
              MAX_USERS: 4
              MAX_ADMIN: 2

            envFrom:
              - secretRef:
                  name: vrising-secret

    service:
      app:
        controller: *name
        type: LoadBalancer
        loadBalancerIP: ${SVC_VRISING_ADDRESS}
        ports:
          steam1:
            enabled: true
            port: *server
            protocol: UDP
          steam2:
            enabled: true
            port: *query
            protocol: UDP

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    persistence:
      config:
        existingClaim: *name
      server:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /mnt/vrising/server
