apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: botkube-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: botkube-config-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        BOTKUBE_DISCORD_BOT_ID: "{{ .BOTKUBE_DISCORD_BOT_ID }}"
        BOTKUBE_DISCORD_TOKEN: "{{ .BOTKUBE_DISCORD_TOKEN }}"
        BOTKUBE_DISCORD_CHANNEL_ID: "{{ .BOTKUBE_DISCORD_CHANNEL_ID }}"
  dataFrom:
    - extract:
        key: botkube
