---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./angelnu.yaml
  - ./backube-charts.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./botkubeio.yaml
  - ./cilium.yaml
  - ./controlplaneio.yaml
  - ./coredns.yaml
  - ./csi-driver-nfs.yaml
  - ./descheduler.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./fairwinds.yaml
  - ./grafana.yaml
  - ./goldpinger.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./intel-charts.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./longhorn-charts.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery-charts.yaml
  - ./openebs.yaml
  - ./piraeus.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stakater.yaml
