---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: valheim
  namespace: games
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      annotations:
        reloader.stakater.com/search: "true"
    image:
      repository: lloesche/valheim-server
      tag: latest
    envFrom:
      - secretRef:
          name: valheim-secret
      - configMapRef:
          name: valheim-config
    ingress:
      main:
        enabled: false
    service:
      main:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${SVC_VALHEIM_ADDRESS}
        externalTrafficPolicy: Local
        ports:
          steam1:
            enabled: true
            port: 2456
            protocol: UDP
            targetPort: 2456
          steam2:
            enabled: true
            port: 2457
            protocol: UDP
            targetPort: 2457
          steam3:
            enabled: true
            port: 2458
            protocol: UDP
            targetPort: 2458

    persistence:
      config:
        enabled: true
        type: pvc
        existingClaim: valheim-data
        subPath:
          - path: config
            mountPath: /config
          - path: data
            mountPath: /opt/valheim
    resources:
      requests:
        cpu: 25m
        memory: 128M
      limits:
        memory: 4G
