apiVersion: v1
metadata:
    name: valheim-secret
    namespace: games
kind: Secret
data:
    SERVER_PASS: ENC[AES256_GCM,data:iE+MUHYWr6g=,iv:fBKKPPp88jVq47LtUwhEPcGXRzYXhIQG67jOgmPudvc=,tag:tNZaCXGOgOrGgQ3S4UINlQ==,type:str]
    WORLD_NAME: ENC[AES256_GCM,data:uIEYTWaGtOy4Caaz,iv:FO7vwcuRc83zGT3ySnyt1Gtlfko8AelN0lx6vX3Sj5Q=,tag:zbFxm4ZjXUptO3J4W/dGdg==,type:str]
    SERVER_NAME: ENC[AES256_GCM,data:9s2cpU0u44ozGZ3l7f5zq0k1NlTsUIqx,iv:cyr/TmVUD6WGGV7KZRmDZqz7ggT0lvTnKy+GjsodZjQ=,tag:aXzJhc1yDM/QTpEk63PmdQ==,type:str]
    ADMINLIST_IDS: ""
    PERMITTEDLIST_IDS: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudUdDRXhYaFF4U3ZZeXJs
            LytqQk10cUlqeHZGa1hNejZyNitMV0lBOGhVCmdJOU9oVWlCWElGUTRuazYwM2ZW
            bzBLcjhscVpjY2JIWDhLanlra3FVUzgKLS0tIE1vL3ErTzBiSUJJVHBwVDB4Z0M2
            L2taZXkwRVdDZVpZMitsV2VvSlFWeUkK7FN1D+v9GpuTFAeEdxE0B+/eJ8/0E2Am
            lOGIraO2fjmj6YGY8Dcapzyq2oqvF0OyLul7Yf8NPUEbcjNMdEUAug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-06T21:19:53Z"
    mac: ENC[AES256_GCM,data:XiUIhxWoVbK3Jhrw6KO79bH5xILX31gKqSItUyDk4gGArtgEEdvsGAIDEGybjWTkz4nQnqDk7kAxKo3fbKZT6DBSi9MPLse0jgJpB8+LEwh89DlhWiHHf9ieUiqDLz7lBJXAvXtNE9/VhWpAKOcuDhVJxwiKU/9RBpxpyFdjAFc=,iv:W07AXlWOgMM1Mg9NGMemq/4hIkQceO5DkMLl5DTwVCY=,tag:Af0B49q9OGDHMf2/I0wLYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
