# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: networking
stringData:
    api-key: ENC[AES256_GCM,data:7jcGuiLIS1OCdXD0+qJcYBNeJOgzLhlB9ZNzbKDU0vxoBrhIdA==,iv:wVjwESD1Z/v+UcnXK9az2TXzbefM1mvy6QIH3vYenok=,tag:mgSke57vSJin+Gu+gzbMNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TWQ5ZktLSFpUbjNoZzRu
            enloUlR2b21lQThoSGV6RXhhRTFCNUp2dENVCnh4M1djdURNd2UrbVNydExlU0Ja
            Z1lLRlpNcHlzT1cyRXovNUVHbllsbEUKLS0tIEFneUhHTTVBWmdtNWEvZjY3dFVy
            WGhNeGQ2Y3hxQVo4R0krNFpwKzc2dlEK+so/kk3mox8QeWxuCGx51ZyCUrZ7Eb20
            DY69vlhKER8wV1JbvpuSnCP8u1kIhJTz4YvjNpoJN8k41PSKbQzHrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-31T20:38:52Z"
    mac: ENC[AES256_GCM,data:e3rCQtvk2vPe5WseoBfvvBLplooxSO7m2zN8szxSN82IEjBVlUXjIzPKmN79kBxb+o8EtItBP7Uyy3+O/qOKuJpy1UWX6IOoq6Fs+LR/kF3cPDoIMsDkTSuCikXyUC5DCiFBxH7z8shbryq+tKVRoFzkBa+Skme83veb6CXAFKg=,iv:06yQ78WexhfxlVFf7LUlSxwuj3nLUtAsBXJcrPUbJSQ=,tag:i6NqQOszX92pHX5SXtFF+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
