# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:KBuxz2lvlPC7en8ldyk4Ng==,iv:Lyr/nAyKv2U+ngM7ZWjOx4/pfuhK6Tkn4yLZZlfQPn4=,tag:lYuAtsQBySAOVQeDdbe4ag==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:9o7v7IF01o027vaWzZnHDfJ/3t4=,iv:TXdQVxbmjE6QKzOLUJU4haq8Hf/Vazyp4ODusDDNpFM=,tag:eznCMkCikPWkrKyhsk5UuQ==,type:str]
    VRISING_SERVER_NAME: ENC[AES256_GCM,data:tWLATGn0dgcmEqpKLVc=,iv:j9TVSvBTFZVSCOg5TLXZ8GBR1FeqEoBYSVW4k9q50LM=,tag:HjREzsRIkMdZobLEPy9llw==,type:str]
    VRISING_SERVER_PASSWORD: ENC[AES256_GCM,data:5JkJ7+Q=,iv:+yPoFTQbSmPAUtAmYXOoyNxpGGznNh5HaGEV4Ti+vVo=,tag:qgDcNtyE/1xtheQtQ5hdbA==,type:str]
    BUCKET_HOST: ENC[AES256_GCM,data:di2tyzc=,iv:YFswse8jEE/ZIQTwUkkSD+lh1zYmYxNOt46VvVtK3zo=,tag:fFN1zvneiL641cch3+pzpw==,type:str]
    LOKI_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:xzPAoML6LWGiSSfA84ZUgA==,iv:fja4Fes87tTImpppb/3zjKG6Ozq/zqwaEstp3g6lGMQ=,tag:ruACVrtjRprQPKeGeVRayQ==,type:str]
    LOKI_MINIO_SECRET_KEY: ENC[AES256_GCM,data:gRwIH5YDv+n8f+3/DT8ncE1gp91SIZ5M,iv:F/jKKT+ihSJK+ydfSVZzHNug0fBDvyHSQ+8Ic3sZQYc=,tag:S2gSxeHVM1A2gkfwoTIhkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMTBucXlvNVl5MUFacFJw
            TVkvb3UrcUtDbXNnL0NzVVlLcmxMUEx3Q25VCmdoa04wb3pCNmh2R0wwVVdGVkMz
            VkVxOHRTbkdkZlIvODIwTkFzZzBieXMKLS0tIGJmSmhJTC80SHFNZHRNNEJkRGhq
            bndNNkREZFlBVDBpdURXT1d5TERBRlkK6kkTs21hngsItRvijjxC1VrratFqoiqT
            D9/UoovRNQd7yZLDY0vyEl7McsF1E6lK4kWV+WLgojPDs5xMXuKLDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-02T21:43:24Z"
    mac: ENC[AES256_GCM,data:snbJlVJtdekaAYWlzKoOf9Y0T94iZMy7N6SGc/SbgAg7fY9EZ2ic+r52dz5RJntnVIPvuL7oiY2s2/uD1Kev1idl1WJRv3dkuAL25J7Q05ne5LxeMbrvGq+UduGKZ22uYuREjZMziAyKA4BDTSEJqe7MT/cHqmKkqx2iCzsvr5Y=,iv:L0MrqWVGKUEcMnEYtgWcK+SSaqvSw776Y7CR067FkQM=,tag:vArEoe/7DFTXVNbUykYtiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
