# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:KBuxz2lvlPC7en8ldyk4Ng==,iv:Lyr/nAyKv2U+ngM7ZWjOx4/pfuhK6Tkn4yLZZlfQPn4=,tag:lYuAtsQBySAOVQeDdbe4ag==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:9o7v7IF01o027vaWzZnHDfJ/3t4=,iv:TXdQVxbmjE6QKzOLUJU4haq8Hf/Vazyp4ODusDDNpFM=,tag:eznCMkCikPWkrKyhsk5UuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMTBucXlvNVl5MUFacFJw
            TVkvb3UrcUtDbXNnL0NzVVlLcmxMUEx3Q25VCmdoa04wb3pCNmh2R0wwVVdGVkMz
            VkVxOHRTbkdkZlIvODIwTkFzZzBieXMKLS0tIGJmSmhJTC80SHFNZHRNNEJkRGhq
            bndNNkREZFlBVDBpdURXT1d5TERBRlkK6kkTs21hngsItRvijjxC1VrratFqoiqT
            D9/UoovRNQd7yZLDY0vyEl7McsF1E6lK4kWV+WLgojPDs5xMXuKLDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-31T20:38:52Z"
    mac: ENC[AES256_GCM,data:w/wMGqa77MbxbDIIM/OIrF9d028S8HZqsiqpOZvdLxSfURkaTIEF3KHz/5WFVYaf7LlGSMny7ACs+LxGAEv43yxgB/J1GtRoLshqpojpZLyXMRvFs5LMnDLQ36LYaI8sUZF8OIm0DP+g/fPR6XvEvDe/0jbWVutYwHD4LZAWcdk=,iv:qQ6S17UDAbIWr/mBCi29K3aafanYmq/3WmjE6s3iizQ=,tag:TFOxgAXXdVvOuc+rn2KAxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
