---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/London
  METALLB_LB_RANGE: 192.168.183.210-192.168.183.225
  METALLB_K8S_GATEWAY_ADDR: 192.168.183.225
  METALLB_INGRESS_ADDR: 192.168.183.210
