---
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
spec:
  talos:
    # renovate: depName=ghcr.io/siderolabs/installer datasource=docker
    version: v1.11.6
