---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app satisfactory
  namespace: flux-system
spec:
  targetNamespace: games
  path: ./kubernetes/apps/games/satisfactory/app
  prune: false # revert
  dependsOn:
    - name: longhorn
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false # no flux ks dependents
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
