apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:VDdmmcprOFphE0Qy78d/xNl1y0oO9CeM/U8dN+IhFcUK92WVbXMGWQ==,iv:E/nGoho0JYDVSqaIygfweOV3iokdq5X2uR8h6ior5Ic=,tag:ZPWfd0iqEgW23uSKfCK1Og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dy85ZFZ2cmwrK2lCWnRl
            SGQ3WmtPMXJZQWZWTFlPdE5HNEw0dWJLVmhBCnNKTys5aVFHZ2ZkQTRQM2VkK0tT
            OWpVWkozQUY3OUx4YkUyK3JjTWJ1RkkKLS0tIE9EVzZyNHlSMm1wemIwQ1JBc0hD
            K2REN3ZHN1Rwc3pzMGdqQml4b2ZDMFEK1MQvqK0/A30YWWamSdh+uWg9xDIYuwA2
            0KLrnKYp/XCR3Tj3nq4O9QuMX0PCpfEiDbKhLzv/CZGg/EkyQQ1Ssw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T13:48:33Z"
    mac: ENC[AES256_GCM,data:5Az4IAMql6balTjukPRUfTJod7L4s8GYfW9QRaayeDT8NulzNw/5zyt2+eqDcWA/oCW4NcQvJyT5pHYPoHenHkNZeSFvfF/j+GeJCcsTs3kbTcXaBMYyT14UB6MtGfVAoP8y+5X6tqUCKung++wgRjltfEEUoERugMIbpiSjJMM=,iv:qH0ELmDVXh2X4g2EDeYWqx/BKFF1vKwx/Vh//BS6374=,tag:jNUl5MeMk50yf18+OcG0bA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
