kind: Secret
ansible_user: ENC[AES256_GCM,data:+WJv1VLh,iv:2OW1DX97qqZBIGqEjPc8Go11zJElwKE1ZCN/0+FCGU4=,tag:gkzd0Visu6sTutNklvSB1Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:ICRwlRRDFeHq8tBKVg==,iv:hdNnX1+xvMVuOveS6ukkfT5MNzLyqspJ0ZHKLZt/olA=,tag:sHf9I1ZwvhC/nKjeQqaFpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWWFzQ2NkT3JyOUd4NDgr
            Y2FGc3p0cnA2dmJuOG9ZMUlFeXBxTlVmRXl3CnExYVZIUitLK1E2Y2pTdUtmM2lR
            c3IyQ3VVTXJiSTNqc1lENzEzcUxEajgKLS0tIGZuc0RuajJwR1RwSnViMVdmSExl
            YjU5RE5CZFFRdjFPQk5ueWlSaWxRZHcKPENGfxY6Qeg2BSwPzHidZjJSBACd+WgV
            /DZTRjDN8/dyIvOSoM6uUlm96Tvi5PTvC08p7wvg4wO1DCEmfYbFkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-31T20:38:52Z"
    mac: ENC[AES256_GCM,data:LPNDU8lWXSFr+TGPNxa6kbW379sfuF0qivi8DQevMxKx7iN03hVD6Oc4+/SKJKKmgrLdHRYU35sGzFuz64nQ8p7kmN4c8qbfUQVrosUWUQ5f4WFYAbh0G8tZEbB6u6bVw4gvg+9m93/r/+W18mriC8UBu1eOjA9a5sB02sc9fUo=,iv:W5aJKYii9wccpJGVb6XeqbfrpDNsuaYw+Z/lJ9+gfZ4=,tag:yjnfAM5qes7MZvnLgmHyPQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
