---
alertmanager:
  interval: 1m
  servers:
    - name: home
      uri: http://vmalertmanager-alerts.observability.svc.cluster.local:9093
      timeout: 10s
      healthcheck:
        visible: false
        filters:
          network:
            - alertname="Watchdog"

alertAcknowledgement:
  enabled: true

filters:
  default:
    - "@state!=suppressed"
