---
alertmanager:
  interval: 1m
  servers:
    - name: home
      uri: http://kube-prometheus-stack-alertmanager.observability.svc.cluster.local:9093
      timeout: 10s
      healthcheck:
        visible: false
        filters:
          network:
            - alertname=Watchdog
            - prometheus=observability/kube-prometheus-stack

alertAcknowledgement:
  enabled: true

filters:
  default:
    - "@state!=suppressed"