apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: valheim-config-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: valheim-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SERVER_PASS: "{{ .SERVER_PASS }}"
        WORLD_NAME: "{{ .WORLD_NAME }}"
        SERVER_NAME: "{{ .SERVER_NAME }}"
        ADMINLIST_IDS: "{{ .ADMINLIST_IDS }}"
        PERMITTEDLIST_IDS: "{{ .PERMITTEDLIST_IDS }}"

  dataFrom:
    - extract:
        key: valheim
