---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app grafana-mcp
  namespace: flux-system
spec:
  targetNamespace: ai-slop
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: toolhive-config
  path: ./kubernetes/apps/ai-slop/grafana-mcp/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 1h
  timeout: 5m
