apiVersion: v1
metadata:
    name: plex-secret
    namespace: media
kind: Secret
data:
    PLEX_CLAIM: ENC[AES256_GCM,data:6FCqxuK25/zzcq81fmy/fKBC1F9n8L4sELV2bpICAva6kPQS,iv:YNZafekgAGLN/ISXCYT5McoJ5u1iWdnHw/J6SPq+9oM=,tag:ye8n9bHbDMF2Nhn8XUEGKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdExNRXhoSFJ6aUo0dXFz
            ZjJNUW5nM20xVEYvTisrWm9WL2ZWN3paL1VNCm9LOG5GMXozVnh5VFpSLzhqWmNG
            V1d6Z2JLTmJtSmR1TVFLbTd5S2t4MGMKLS0tICtoMG9PL2ozT3lPWVlSek04eWZJ
            c3RYV3ovcnN6L1g4cHNpV1RhSjF3MHcKQUmNqwor+4Wsl979jrqqEijqSAL+Xfdi
            ue0GkiCVoNWqpTK0T+bNMj/AYBh0o0M/n7FzyWxefewkVId92QrKBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-22T09:57:55Z"
    mac: ENC[AES256_GCM,data:gPxMyBijNaaFLp5hjYYhtTkkmW8XUvYajvYXCPh+hK5V8gLUnXk0XXXx7ymkhiHwP9VXcsynd8oRq0oZwUQ9nwGJTxL6fJLlng0NN6f4xe8q6d8VAode9BcmxueqlMABvqKAzGmu4o4QUOQPw/ViKSt8PUqCE2wb2n4zmXVVl14=,iv:IJcTg4tZnUMsZJ0M8yxQmK19OjP0hvKPS5lYPwFt9jQ=,tag:wJsjJLoKlRLBM2MJwFkdAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
