apiVersion: v1
metadata:
    name: valheim-config-secret
    namespace: games
kind: Secret
data:
    SERVER_PASS: ENC[AES256_GCM,data:iE+MUHYWr6g=,iv:fBKKPPp88jVq47LtUwhEPcGXRzYXhIQG67jOgmPudvc=,tag:tNZaCXGOgOrGgQ3S4UINlQ==,type:str]
    WORLD_NAME: ENC[AES256_GCM,data:uIEYTWaGtOy4Caaz,iv:FO7vwcuRc83zGT3ySnyt1Gtlfko8AelN0lx6vX3Sj5Q=,tag:zbFxm4ZjXUptO3J4W/dGdg==,type:str]
    SERVER_NAME: ENC[AES256_GCM,data:9s2cpU0u44ozGZ3l7f5zq0k1NlTsUIqx,iv:cyr/TmVUD6WGGV7KZRmDZqz7ggT0lvTnKy+GjsodZjQ=,tag:aXzJhc1yDM/QTpEk63PmdQ==,type:str]
    ADMINLIST_IDS: ""
    PERMITTEDLIST_IDS: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudUdDRXhYaFF4U3ZZeXJs
            LytqQk10cUlqeHZGa1hNejZyNitMV0lBOGhVCmdJOU9oVWlCWElGUTRuazYwM2ZW
            bzBLcjhscVpjY2JIWDhLanlra3FVUzgKLS0tIE1vL3ErTzBiSUJJVHBwVDB4Z0M2
            L2taZXkwRVdDZVpZMitsV2VvSlFWeUkK7FN1D+v9GpuTFAeEdxE0B+/eJ8/0E2Am
            lOGIraO2fjmj6YGY8Dcapzyq2oqvF0OyLul7Yf8NPUEbcjNMdEUAug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-11T19:57:32Z"
    mac: ENC[AES256_GCM,data:hCRrDKpdcyrwVFf5BhBAvn0hap9jjMCX2Bszwr7Kv21zyCDeT/6WSNJcoQLE67KLvAsWNiY9Dmru/HKizZ2qgr0VJiKYaSCTmqZay8/KmkU+hXiIEPXdY//0dm4Eb22Nk+pt8+zhTeOsVmN9TVDuicIVjqFMTSVSwMF24KKzZso=,iv:wmy1HR5Z5yqWmXcu4wxp98cGdrYWkNxALQPaVnEortw=,tag:GxOMuxHuluML2CYonKfnyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
