# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-external-secret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: "valheim-volsync-r2-secret"
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .restic_repository }}"
        TEST: "{{ .test }}"
        RESTIC_PASSWORD: "{{ .what }}"
        # RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        # AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        # AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: r2-volsync-config