---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "valheim-bootstrap"
spec:
  trigger:
    manual: restore-once
  restic:
    repository: "valheim-volsync"
    copyMethod: Snapshot
    volumeSnapshotClassName: "longhorn-snapclass"
    cacheStorageClassName: "longhorn"
    cacheAccessModes: ["ReadWriteOnce"]
    cacheCapacity: "8Gi"
    storageClassName: "longhorn-snapshot"
    accessModes: ["ReadWriteOnce"]
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    capacity: "10Gi"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "valheim"
spec:
  sourcePVC: "valheim"
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: "Snapshot"
    pruneIntervalDays: 10
    repository: "valheim-volsync"
    volumeSnapshotClassName: "longhorn-snapclass"
    cacheCapacity: "8Gi"
    cacheStorageClassName: "longhorn"
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: "longhorn-snapshot"
    accessModes: ["ReadWriteOnce"]
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 7
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "valheim-bootstrap"
  resources:
    requests:
      storage: "10Gi"
  storageClassName: "longhorn"
