---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: snapshot-controller
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: piraeus-charts
        namespace: flux-system
  maxHistory: 2
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      volumeSnapshotClasses:
        - name: longhorn-snapclass
          annotations:
            snapshot.storage.kubernetes.io/is-default-class: "true"
          driver: driver.longhorn.io
          deletionPolicy: Delete
          # Ref: https://github.com/longhorn/longhorn/issues/2534#issuecomment-1010508714
          parameters:
            type: snap
      serviceMonitor:
        create: true
    webhook:
      enabled: false
