---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app radarr
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  targetNamespace: media
  path: ./kubernetes/apps/media/radarr/app
  prune: false # revert
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false # no flux ks dependents
  interval: 30m
  timeout: 5m
  dependsOn:
    - name: volsync
    - name: ingress-nginx-internal
    - name: longhorn
  postBuild:
    substitute:
      APP: *app
      CLAIM: radarr-config
      VOLSYNC_CAPACITY: 15Gi
