---
# yaml-language-server: $schema=https://raw.githubusercontent.com/JJGadgets/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app mosquitto
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: eclipse-mosquitto
      tag: 2.0.16
    global:
      nameOverride: *app
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${MQTT_SVC_ADDRESS}
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            primary: true
            port: 1883
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    configMaps:
      config:
        enabled: true
        data:
          mosquitto.conf: |
            listener 1883
            allow_anonymous true
            persistence false
            connection_messages false
    #       mosquitto.conf: |
    #         listener 1883
    #         allow_anonymous true
    #         persistence true
    #         persistence_location /mosquitto/data
    #         connection_messages false
    persistence:
      config:
        enabled: true
        type: configMap
        name: mosquitto-config
        mountPath: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf
