---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: toolhive
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
spec:
  ingressClassName: internal
  rules:
    - host: &host mcp.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vmcp-tools-gateway
                port:
                  number: 4483
  tls:
    - hosts:
        - *host
