apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aiden-exporter-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: aiden-exporter-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        FELLOW_EMAIL: "{{ .FELLOW_EMAIL }}"
        FELLOW_PASSWORD: "{{ .FELLOW_PASSWORD }}"
  dataFrom:
    - extract:
        key: aiden-exporter
