---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
  namespace: services
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      paperless:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.8.6
            env:
              PAPERLESS_CONSUMER_POLLING: 60
              PAPERLESS_CONSUMER_RECURSIVE: "true"
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
              PAPERLESS_CONSUMPTION_DIR: /nas-data/consume
              PAPERLESS_DATA_DIR: /nas-data/library
              PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"
              PAPERLESS_EXPORT_DIR: /nas-data/export
              PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: HTTP_REMOTE_USER
              # PAPERLESS_MEDIA_ROOT: /library/media
              PAPERLESS_OCR_LANGUAGES: eng
              PAPERLESS_OCR_LANGUAGE: eng
              PAPERLESS_PORT: &port 80
              PAPERLESS_REDIS: redis://localhost:6379
              PAPERLESS_TASK_WORKERS: 2
              PAPERLESS_TIKA_ENABLED: 1
              PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://localhost:3000
              PAPERLESS_TIKA_ENDPOINT: http://localhost:9998
              PAPERLESS_TIME_ZONE: Europe/London
              PAPERLESS_URL: https://paperless.${SECRET_DOMAIN}
              USERMAP_UID: 1026
              USERMAP_GID: 100
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 11m
                memory: 2048Mi
              limits:
                memory: 2048Mi

          gotenburg:
            image:
              repository: thecodingmachine/gotenberg
              tag: 8.5.1
            env:
              - { name: DISABLE_GOOGLE_CHROME, value: "1" }

          redis:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 7.2.4

          tika:
            image:
              repository: ghcr.io/paperless-ngx/tika
              tag: 2.9.1-full

    service:
      app:
        controller: paperless
        ports:
          http:
            port: *port

    ingress:
      app:
        className: nginx
        annotations:
          hajimari.io/icon: file-multiple
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        existingClaim: paperless-data-v2
        advancedMounts:
          paperless:
            app:
              - path: /usr/src/paperless/data
      library:
        type: nfs
        server: ${NAS_ADDR}
        path: /mnt/external/Documents
        globalMounts:
          - path: /nas-data
