apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  storageClassName: paperless-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${NAS_ADDR}"
    path: /mnt/external/Documents
  mountOptions:
    - nfsvers=4
    - nconnect=8
    - hard
    - noatime
    - noac
