---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.11.3
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery-charts
        namespace: flux-system
  values:
    worker:
      config: ### <NFD-WORKER-CONF-START-DO-NOT-REMOVE>
        core:
          sources:
            - custom
            - pci
            - usb
        sources:
          usb:
            deviceClassWhitelist:
              - "02"
              - "03"
              - "0e"
              - "ef"
              - "fe"
              - "ff"
            deviceLabelFields:
              - "class"
              - "vendor"
              - "device"
          pci:
            deviceClassWhitelist:
              - "0200"
              - "03"
              - "12"
            deviceLabelFields:
              - "class"
              - "vendor"
              - "device"
              - "subsystem_vendor"
              - "subsystem_device"
          custom:
            - name: intel-gpu
              matchOn:
                - pciId:
                    class: ["0300"]
                    vendor: ["8086"]
            - name: zzh
              matchOn:
                - usbId:
                    vendor: ["1a86"]
                    device: ["7523"]
    ### <NFD-WORKER-CONF-END-DO-NOT-REMOVE>
