---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: grafana
spec:
  image: docker.io/grafana/mcp-grafana:0.16.0-alpine@sha256:6711096c67ba30f949bae638ab789afa910840f29994e5f99e289c0864fde807
  args: ["-t", "stdio"]
  transport: stdio
  groupRef:
    name: mcp-tools
  env:
    - name: GRAFANA_URL
      value: http://grafana.observability.svc.cluster.local
  secrets:
    - name: grafana-mcp
      key: token
      targetEnvName: GRAFANA_SERVICE_ACCOUNT_TOKEN
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          resources:
            limits:
              cpu: "500m"
            requests:
              cpu: "10m"
  resources:
    limits:
      cpu: 200m
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 100Mi
