---
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: grafana
spec:
  image: docker.io/grafana/mcp-grafana:0.15.2-alpine@sha256:0ecef01982d3e140c8cacba8df9d1be04bd11ec8f249f57abb350bf4444a0a49
  args: ["-t", "stdio"]
  transport: stdio
  groupRef:
    name: mcp-tools
  env:
    - name: GRAFANA_URL
      value: http://grafana.observability.svc.cluster.local
  secrets:
    - name: grafana-mcp
      key: token
      targetEnvName: GRAFANA_SERVICE_ACCOUNT_TOKEN
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          resources:
            limits:
              cpu: "500m"
            requests:
              cpu: "10m"
  resources:
    limits:
      cpu: 200m
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 100Mi
