---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: grafana
spec:
  image: docker.io/grafana/mcp-grafana:1.3.0-alpine@sha256:4900f808accbb06b9c5d09e224a153966c2d2a04015ddf20f8050ade9d906635
  args: ["-t", "stdio"]
  transport: stdio
  groupRef:
    name: mcp-tools
  env:
    - name: GRAFANA_URL
      value: http://grafana.observability.svc.cluster.local
  secrets:
    - name: grafana-mcp
      key: token
      targetEnvName: GRAFANA_SERVICE_ACCOUNT_TOKEN
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          resources:
            limits:
              cpu: "500m"
            requests:
              cpu: "10m"
  resources:
    limits:
      cpu: 200m
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 100Mi
