---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: botkube
  namespace: flux-system
spec:
  targetNamespace: observability
  path: ./kubernetes/apps/observability/botkube/app
  prune: false # revert
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  timeout: 5m
