apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:6Es58UdelS+4gpNNxQtkJ3Nn4UUYqbfKi4Zf+PhW82wREHxbUH+J5RhfjQjgiTOcuX0iWXqSov+V+CWc,iv:gUaGpWeXgP3NBzJ1YIQYihzNy6vZwM5Ebj8YmrcRcaM=,tag:+Q5JoZ/+Q/STWPgSn1k/MQ==,type:str]
    username: ENC[AES256_GCM,data:K9scOK8=,iv:OARWWCjjP2sLAg2IY2TODapvZjqh8xtDiPKVvNvRd6c=,tag:VPuGULLTGSXI+ifMnRd2MQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SUdJSUVEYnpjNTRtdDgv
            U2I4c2p6VzdZd0xVK3NKWjV0R1pnS2R6VG5NCmhrY1U4MmFuVHRPcldEL2N4Z1JH
            UFA0dXZZd2Zod3p5TUVaRXFGSjJlbG8KLS0tIGxtUUhmaUd1dVZuL29QRmpWaVkr
            RmVsbW9GNm9ucnUyN3Y0STNVQ1lRTWsKEjV/Ye7hpiycXEBAgbzYY9z+7i4rmnEi
            Jo0IExABk9l7Rp0YUUbQQl1pqYmyrLS8oqcWQbx3nNDUMFu+n2/xxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T13:48:49Z"
    mac: ENC[AES256_GCM,data:f6LWr//0inaJ/FQGAXDrNQqoLsrustLaZlqRnnKg5qLGhxT8CKze4hZ9oJ4PdyP3tVam2wzrEiqxKHqzKPLAphym0m59k5qSBtOaKvwImxfNI3MEH+pM6Cs/g/COuPLeEg+4Th/fs3QMvBeUMFJH+cMRfLLxokAYlTTXorIywXo=,iv:EixWuJV7iRYgfoYDsCQdECGj9RfXKr3hVQBtqZydFVE=,tag:7zXFs/c9xQuY1zkPrS2Nhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
