---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  - flux-system
  - games
  - kube-system
  - longhorn-system
  - media
  - monitoring
  - networking
  - storage
  # - system-upgrade
