---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/London"
  NAS_ADDR: 192.168.183.204
  SVC_VRISING_ADDRESS: 192.168.183.230
  SVC_VALHEIM_ADDRESS: 192.168.183.229
  SVC_PLEX_ADDR: 192.168.183.224
  MQTT_SVC_ADDRESS: 192.168.183.228
  HOMEKIT_ADDRESS: 192.168.183.249
