apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:txXoIJOhYL7qxzm9cMmIOImepp4=,iv:TSALGueEMmohfZFtyBWqXPm7o24Ln6wb/qHl5rUBMPU=,tag:+Ew3u110MnNos87eBAIm+g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:8JKSigt6+8ub+jvMpv5mc+A2QJrhnB0gTLvYGa0VK5IGgUv2,iv:Xj6x9RQNpHrGl3lhwT6GZe1qrdIa0ciBn02viWV2S7k=,tag:ZS5yU6fAPorNehBeFCV0+w==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:/0VsdMbOZCFYTKwjgSQtOQ==,iv:Ma1hXW7McvLKVX04YJjyKI0uY3XoAHCbkTJy9HreNMA=,tag:oHx+H+eHuNo7v2VndQ+OOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUy9NeU9LYVg1My9oTXo1
            eXZTNG1pRVpseE9nQXEwdEdEc0M4aDdGdXhvCkJiOG94VnlDZEZDS2lBenpmQmlp
            bFN2OXBJWHlzaGdOTzgvTmxTbXV2TkUKLS0tIENualhCd2VsY2hLSzhpUXV3RG12
            UjhuWFNMVU5CekFkc0x4YlpjVXJOVGMKYxcaMcx6wHI2rTfgoclRcU8SSNQPLK5j
            O4RiAarKcjuFAMd31xJ7j+Z0k9ujerEp7Tha79x3jW91KMdq/mLtaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T13:48:32Z"
    mac: ENC[AES256_GCM,data:zHTGhHlP5qUCy659nOW6TaXYortHs5JYJXCY+cX435B49kctcYtmGqSZWWZcXVvpsr+3F3jiDQihlbkyU8trhYJoIFGurbwGb6pedew5d1g8fPTUfA1Fw0Z4XpErab+vTsKGMrcOEBNmgR2dd5O0lUatZYefAUpJYZ7aC+XDrp0=,iv:e/76ITXTBrYzsvj7leCgsa07tNUgncyOREQGZVrKxhA=,tag:fl/htbo23p+3PCtQcZtW7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
