---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sonarr
  namespace: flux-system
spec:
  path: ./kubernetes/apps/media/sonarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: volsync
      namespace: storage
  postBuild:
    substitute:
      APP: *app
      CLAIM: sonarr-config-v1