---
apiVersion: storage.k8s.io/v1
kind: StorageClass
reclaimPolicy: Delete
provisioner: driver.longhorn.io
parameters:
  # used for volsync to copy from.
  # we set this to 1 replica for faster restores from the snapclass
  dataLocality: disabled
  numberOfReplicas: "1"
  replicaAutoBalance: best-effort
  staleReplicaTimeout: "30"
  # This is required for Longhorn 1.10, csi storage capacities are not created without it
  # https://github.com/longhorn/longhorn/issues/11906
  dataEngine: "v1"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
metadata:
  name: longhorn-snapshot
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
reclaimPolicy: Delete
provisioner: driver.longhorn.io
parameters:
  # we set this to 2 replica for less copies of the cache, which can be blown away safely.
  dataLocality: disabled
  numberOfReplicas: "1"
  replicaAutoBalance: best-effort
  staleReplicaTimeout: "30"
  # This is required for Longhorn 1.10, csi storage capacities are not created without it
  # https://github.com/longhorn/longhorn/issues/11906
  dataEngine: "v1"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
metadata:
  name: longhorn-cache
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-cnpg
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
# WaitForFirstConsumer delay binding and provisioning of PV until a Pod using the PVC is created.
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  # This is required for Longhorn 1.10, csi storage capacities are not created without it
  # https://github.com/longhorn/longhorn/issues/11906
  dataEngine: "v1"
  numberOfReplicas: "1"
  staleReplicaTimeout: "1440" # 1 day
  fsType: "ext4"
  dataLocality: "strict-local"
