apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:PXBMQkf79WDMzxfszc3HAUZC+FloS07rYzFoaCWI/k1XaZSN,iv:2tktCllath6HmzOUciqZA+9b0PozCu8oS9yOucBghGs=,tag:zNvx0kRZce7hDUKHGgKKjA==,type:str]
    credentials.json: ENC[AES256_GCM,data:9uPM3/91mclOl/mgThYgVbSUVOYh5IkNkj1lDpvIHy51XXkU6vNRV7EcBP0HqnlGCLNcQAzlmUd4jxdQ0accbYgPTCoH9UwDePHsC5MddIZTkv7rdHwgQwWURkEE9EyGCPCEOiKa9TzkCx1to2nvt9LMQANPoj8eAnRmFg2n6Q/tsuie+ma1E7b6g7fgfejm/YvgPucYKxYwNmiZlG0NJAm4Y32bLHJTfEZVvwT3+A==,iv:Y51kyOhIb+C0E7aTnrlr1QqGiULADZSPylds+NnMf5w=,tag:Yf5OzUrBG6tmYmZEc0SlSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWS9ra3l5UXlnbEFUM2hp
            VVl6QnN3eHdySXpJVndMQjRLVEJSc29TYmlnCjFXSldJT0ptRFRxdGErR05aK00v
            MWRuVVZYVmVSc3RUZGkwSGk1N25wMDAKLS0tIEN1YjE4Ykw3UnFadkhkZVM0bi9P
            VkxTL0lwSlJ2dzlEak9LaXBORXFGMlEKEbgryJDvlQC1TyfF232moHXYWwiEw2Ao
            MkSiCwypFmac4Y2TA1wOEeoOmREfj42mPeWDbWQca2M45riAleag/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T13:48:32Z"
    mac: ENC[AES256_GCM,data:yi1aLkixImOaLF26ajC90p8h670eVMU2SncSFNtCM3ePmZ6yJb2ToqoYmtNdslQ14Aj67eHcRSWaE9jZQYpatL5Uk7T5nX7m+EjQ+rXoL8zWgiSoJw8VItGo22sbXDQCUn5ueZmI9Pa3Gtj5xG7BCj8yCz/yuu4o9ohE5sFQ3ZI=,iv:UmnHqagDnuOurtYSsQ8bD6dBxix2TJaXQ3U9VXCNMgo=,tag:tstMSD8sfjNZrmt5f9AyrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
