---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: satisfactory
spec:
  endpoints:
    - dnsName: "satisfactory.${SECRET_DOMAIN}"
      recordType: A
      targets: ["${SVC_SATISFACTORY_ADDRESS}"]
      providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: "false"
