---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name satisfactory
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn:
    - name: longhorn
      namespace: storage
  install:
    replace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      strategy: rollback
    cleanupOnFail: true
  uninstall:
    keepHistory: false

  values:
    controllers:
      satisfactory:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            nameOverride: *name
            image:
              repository: ghcr.io/wolveix/satisfactory-server
              tag: v1.9.10

            env:
              TZ: "${TIMEZONE}"
              ROOTLESS: "true"
              AUTOPAUSE: "true"
              MAXPLAYERS: "4"
              AUTOSAVEINTERVAL: "60"
              AUTOSAVENUM: "30"
              MAXTICKRATE: "120" # default is a low 30
              NETWORKQUALITY: "3" # 0-3, 3 is Ultra (default)
              AUTOSAVEONDISCONNECT: "true"
              CRASHREPORT: "false"
              TIMEOUT: "300"

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL

            probes:
              startup:
                enabled: false
              liveness:
                enabled: false
              readiness:
                enabled: false

            resources:
              requests:
                memory: 6Gi
              limits:
                memory: 20Gi

    service:
      app:
        enabled: true
        controller: *name
        type: LoadBalancer
        allocateLoadBalancerNodePorts: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "satisfactory.${SECRET_DOMAIN}"
          lbipam.cilium.io/ips: "${SVC_SATISFACTORY_ADDRESS}"
        externalTrafficPolicy: Cluster
        internalTrafficPolicy: Cluster
        ports:
          game-udp:
            enabled: true
            primary: true
            port: 7777
            protocol: UDP
          game-tcp:
            enabled: true
            port: 7777
            protocol: TCP
          messaging-tcp:
            enabled: true
            port: 8888
            protocol: TCP

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    persistence:
      config:
        enabled: true
        existingClaim: *name
        globalMounts:
          - path: /config
      server-cache:
        enabled: true
        existingClaim: "sf-gamedata"
        globalMounts:
          - path: /config/gamefiles
