---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sf-gamedata
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: longhorn
