---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldpinger
spec:
  interval: 30m
  chart:
    spec:
      chart: goldpinger
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: goldpinger
        namespace: flux-system
      interval: 30m
  values:
    image:
      tag: 3.10.2

    ingress:
      enabled: true
      className: internal
      annotations: 
        hajimari.io/icon: "table-tennis"
      hosts:
        - host: &host goldpinger.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: prefix
      tls: 
        - hosts:
          - *host

    resources: {}
      # limits:
      #  cpu: 100m
      #  memory: 128Mi
      # requests:
      #  cpu: 100m
      #  memory: 128Mi

    updateStrategy: {}
      # type: RollingUpdate
      # rollingUpdate:
      #   maxUnavailable: 1

    serviceMonitor:
      enabled: true