---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hajimari
  namespace: flux-system
spec:
  targetNamespace: default
  path: ./kubernetes/apps/default/hajimari/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false # no flux ks dependents
  interval: 30m
  timeout: 5m
