apiVersion: v1
kind: Secret
metadata:
    namespace: monitoring
    name: botkube-secrets
    labels:
        botkube.io/config-watch: "true"
stringData:
    BOTKUBE_DISCORD_BOT_ID: ENC[AES256_GCM,data:cqB8UviFMztvi2nyBHO+ut5F,iv:twHwizcFWpvdKWdpxLqvs9h2ZNklrCza0l/UjrD9iG0=,tag:JG/REKznTTeiJsPf1kmAXw==,type:str]
    BOTKUBE_DISCORD_TOKEN: ENC[AES256_GCM,data:13tzB0gJmVJGDUblZiqs7ccurnuKVUdh9ZiY4PRdPECxlKIjlhDYi9tg0DMnbQidEBhwW+oWKBCwJLm8E1t7yyt8oU0XIQ==,iv:dzzh7pdoPtOSWhv7y4njWDCAt8/mnwDR7+IoGmdUJHA=,tag:lKxRumanHwqyifI4nkIMQA==,type:str]
    BOTKUBE_DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:Z22D7C4Df8/oFG7jyR4yI1y1tg==,iv:mW/ifhyZyKZWAuxlQYE3YaX7nzxCQKijfvBrFLvnDAQ=,tag:BoMyvifqsf4GGxIRoVUQ2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMDBkUEM0QXo0b2RvNUNY
            U3UwUTNUMlAxem11Mld0TVg1NWtSUlM5V3lFCllDbzI0Z1JZNnZaNENCQytpQ29S
            eWNNVEpRQ3liZDZnWUVtQzJ4KytwSVUKLS0tIHNPamNleVV1U2FSVXVRMmpHcEth
            WlZoSkZIbDdEU285Nkk1TitSelR5RXMKgTsVRtslqk9vh+CskfeS4j2DYX+vaHAn
            c2EytbnxlkRQk15PWcddmQjOJ2spfzPcWNlWSW4XSMtDYu5v9Uqwsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-07T14:37:50Z"
    mac: ENC[AES256_GCM,data:WEpYFiYK8bwqfqzQMLQ3mqweR7Odospwu7KyJ4LWiRcsXiBauKA0eSosG2CmwC8SRRdgn8DlH4a0Jvt34+B7ah1ys3AVJyOnI7bZnTqdobpcyYA6WMHNnA5NQeD3o+bx8skEGoXJe/CXHw+svZxhvAtkoKuB1Y0jQqai6ktcQ1k=,iv:a3+vOG2rtNpcbs1AyXHrD+7TzAPQpYLzegYrJ1N2x50=,tag:VONtf/Mo5WZl0mXnfuNwwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
