apiVersion: v1
kind: Secret
metadata:
    namespace: monitoring
    name: botkube-communication
stringData:
    comm_config.yaml: ENC[AES256_GCM,data:7K7opmhIN/1ZrZXiCv058KMhdu/idVkxiXyRukJdcZTGwW2HvT/sTVoGRjLtqaHZKx+iRcngsq4Gaqdiagi2M1aDN20oiwYZ2h/L7yIoighUkoYN3oIzXpIIbE60ZjBLvCNG8gNJRcSykHb5LGuGTMGo24exm/pPRAQybriWmH9ky4dw0ErMLkzsuMLJg8M05Yhof+vNwEoS/K3AsL57HZpPzHpNpcE1HuKE7xs9jjwUaQc1gyS6g35x0dvnKHBxKxLr/1/hA5NRMdNJBphBvEoJo1q0tVogn1pG3hEMzCXGFvVZvDgtxhPL9PRbavhgT2L0PPP875r7erTIy/IEHMSDaQ6ILQSzo4FpED/30H8rV8PYDeIzS7nwg3X5Y8OP8ELPRpV8rY6GZourmvZHKXqeik83ujHidyXEm4NVAPITSp2jKVcN5UuXLtkaePkH7is2i0fU0osX5JkiIOPzJWxrOJI/FbLnJShTyjWi7zpDi4/w5TEFs2W7MDRK4MLSp6mJNFA2lOinfN+Oki665WW1OO/NZTxIDVKHq+uXld1JMXZialPuWqxVhJ4Nm5kztGZumWM5xE4AjoMQwfKjoVCjCdecrVzpMj9DxB1rDZ1YaZd6V8CQKg3ZVbCeU/OLni17QCF86ftaKazN5/4QMFk6bbecJ/NIHY6QdLySg1ZrEIUAThqNYOiDVFPVg2szOP4vauTt/IEy+6IUwez9R19Q8GqxbuknCoBwW6+YdXzRCyGcn+HvBKlkja8TK4MWT8OTWXv2Lk3O7bY=,iv:h+BdiyxpbBkf2pzz9UZuRDnU6bZ+OXkzekXUo0FBd3s=,tag:Ou2wyuN9l0ZQ7cyBp4AfFw==,type:str]
##  stringData:
##    comm_config.yaml: |
# as a string
# communications:
#   'default-group':
#     discord:
#       enabled: false
#       token: 'DISCORD_TOKEN'
#       botID: 'DISCORD_BOT_ID'
#       channels:
#         'default':
#           id: 'DISCORD_CHANNEL_ID'
#           notification:
#             # -- If true, the notifications are not sent to the channel. They can be enabled with `@Botkube` command anytime.
#             disabled: false
#           bindings:
#             executors:
#               - kubectl-read-only
#             sources:
#               - k8s-err-events
#               - k8s-recommendation-events
#       notification:
#         # -- Configures notification type that are sent. Possible values: `short`, `long`.
#         type: short
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMDBkUEM0QXo0b2RvNUNY
            U3UwUTNUMlAxem11Mld0TVg1NWtSUlM5V3lFCllDbzI0Z1JZNnZaNENCQytpQ29S
            eWNNVEpRQ3liZDZnWUVtQzJ4KytwSVUKLS0tIHNPamNleVV1U2FSVXVRMmpHcEth
            WlZoSkZIbDdEU285Nkk1TitSelR5RXMKgTsVRtslqk9vh+CskfeS4j2DYX+vaHAn
            c2EytbnxlkRQk15PWcddmQjOJ2spfzPcWNlWSW4XSMtDYu5v9Uqwsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-02T13:31:44Z"
    mac: ENC[AES256_GCM,data:2c8BNnXt/4BVAGoGFQO8A+GZrXRtGNCTIi9hM2NvWivKt5N/HjnkAPvvLZOrUTlqF6ShesupFopi/OSNntt2CALMqelJXMwl+Pm/7vjZfw/+HvwtZ9iG7WO0HwZa6pI2r28OPCDbX0mj7hDah4sZDWAYzRLKE7hcvL1ENMidHbQ=,iv:C0EnblEJA67VQ39pU2Ih57RkgnIS7Yw7xrsnZkQNPLg=,tag:KG4F3Kede+YlAlU8oRAVJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
