apiVersion: v1
kind: Secret
metadata:
    namespace: monitoring
    name: botkube-communication
stringData:
    comm_config.yaml: ENC[AES256_GCM,data:n2EYgPx7KMjBpcUCOGi6pWwBFwhMpABsdQCLAReHdi/D2rJCXzfXhAjo7OYM4Q8rcwIE5AGX+OAEQP0kQTZxcNohFz07GkpHmqKp/YGLWnMoUuUx9Qf2m8Nnc4S1ELzQQDO7uKz1x2GPspf3e7HVbD/5qCb0/jGp2aUFl9rA8136BexhSAGCD6qpkidb6QVjbTAy6hejYIOZKyW0PqUEknN4+vtnvc2m45Gxs1Nj5hJ9FQ1sqtNWRG2gEw74/pi5OkylIF7FfWVZQUiDnUpkFZ7yyJMI4VXRrBve8O7TLzDhRpFMPirQCPQXRFaURINeFHulEYgOwVpb453i+eyGFm1v8uZzob2M/Om98kLHOm9lw9Cpn9IA0DZnZ/zAxjypohDK5ORNLFm8+DKnZQBJKMEzV+G8X/cV4Dd6cl6gHEn1uOma3q7GbXg+igfbD+ANL9Q+74RY8T5S6pcFOA88Xdtv8cjTY9GnHiu6+0Ide0UbLpfp4022qyshX1l1kFNnmdVe/2pmH/6R6zJpsZH2bBw6SvhZW1TDkLdjYHCX/hKzHYfykNSzh1Y+78KJez8XFpR+Kntr5Tk7BNoMzBFVf4QT8PH6HAe27tDDBZYbYfjAkwqx4ZAHTi/dcW9MQY09sqOnr/4HkKilO3OqwTVOQNXLVQTz+8US7Mj894UZNZHw7eEyeztIIb+UgEf3wJeB3GJx0cASEDVYPJLcRnP16KSGmTT3ZtQZqHGxbsX1/x+HDpE0pS3Q0cEnMEVy5jkthulAVm4FzdJXV9pYkkzP1sQXObagmgw2uMvDikuJYpwkivzN5iWL9OK6H+YjyvfqSy7oWo510pL+Kz7Toag=,iv:knvgl/eL8RChxfGmVL2Yawvpr5gj/MCWUUxBd8Zb8m4=,tag:sua/tIHO4bq5NCsEIB5VeA==,type:str]
##  stringData:
##    comm_config.yaml: |
# as a string
# communications:
#   'default-group':
#     discord:
#       enabled: false
#       token: 'DISCORD_TOKEN'
#       botID: 'DISCORD_BOT_ID'
#       channels:
#         'default':
#           id: 'DISCORD_CHANNEL_ID'
#           notification:
#             # -- If true, the notifications are not sent to the channel. They can be enabled with `@Botkube` command anytime.
#             disabled: false
#           bindings:
#             executors:
#               - kubectl-read-only
#             sources:
#               - k8s-err-events
#               - k8s-recommendation-events
#       notification:
#         # -- Configures notification type that are sent. Possible values: `short`, `long`.
#         type: short
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMDBkUEM0QXo0b2RvNUNY
            U3UwUTNUMlAxem11Mld0TVg1NWtSUlM5V3lFCllDbzI0Z1JZNnZaNENCQytpQ29S
            eWNNVEpRQ3liZDZnWUVtQzJ4KytwSVUKLS0tIHNPamNleVV1U2FSVXVRMmpHcEth
            WlZoSkZIbDdEU285Nkk1TitSelR5RXMKgTsVRtslqk9vh+CskfeS4j2DYX+vaHAn
            c2EytbnxlkRQk15PWcddmQjOJ2spfzPcWNlWSW4XSMtDYu5v9Uqwsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-07T14:23:09Z"
    mac: ENC[AES256_GCM,data:VzBv0Lne1PVznx9I/DJivI1F8lfvIlXGRWm8LZm+QVAgk88faJZ/eXyn+2dOgEsALZOEfX+ZXv01t5G577MfwMlXwKJs2+/s8qPzQNBeZfj/hywd0jgKTr/zwvpxJ+unbhVHC+oJbCp+tOKFg5DPcXpRjViNLKS5mMXHCFPxduQ=,iv:oVEnQPMsoDq840Dag5GBeUVHE52l1xAOA0Q3WpnEocQ=,tag:EhcGqBVJqyex5RME7o9Mow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
