apiVersion: v1
kind: Secret
metadata:
    namespace: monitoring
    name: botkube-secrets
    labels:
        botkube.io/config-watch: "true"
data:
    BOTKUBE_DISCORD_BOT_ID: ENC[AES256_GCM,data:ukZef+TJ/6ZOpWItvkkxAO3L,iv:i9Itec+a2Lj20FAVNNmxD45ZemF9lYzIgNyAMIPbHuk=,tag:giQhcYD0rJN6WHZA85CtsQ==,type:str]
    BOTKUBE_DISCORD_TOKEN: ENC[AES256_GCM,data:U58LzmEFkcSz/iZctmUu5XnAGYrspOvT40M6AbWgzGpTXzys/rT4A6pFxuwDZ58F0SWl1b6g6V8x9CsN8tlfqg8d+wou4A==,iv:TpwJLT3DvbHe5CgEEEz1RJ/YwlHBU808ZCSYwGni3tQ=,tag:ynJzuMp+FBOQJShzaJrgvQ==,type:str]
    BOTKUBE_DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:x+MCBFyfcy5s8LSL9zaQBu2mgQ==,iv:WIwKupnPDs/1/Op0QRSETZyF9hz2INsnLhFOngJRIZU=,tag:ZJI/JgKic9cjRFMimYkmdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMDBkUEM0QXo0b2RvNUNY
            U3UwUTNUMlAxem11Mld0TVg1NWtSUlM5V3lFCllDbzI0Z1JZNnZaNENCQytpQ29S
            eWNNVEpRQ3liZDZnWUVtQzJ4KytwSVUKLS0tIHNPamNleVV1U2FSVXVRMmpHcEth
            WlZoSkZIbDdEU285Nkk1TitSelR5RXMKgTsVRtslqk9vh+CskfeS4j2DYX+vaHAn
            c2EytbnxlkRQk15PWcddmQjOJ2spfzPcWNlWSW4XSMtDYu5v9Uqwsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-07T14:36:12Z"
    mac: ENC[AES256_GCM,data:iyoYsjbovJPIWYcJsqhhSchzQKBUaQeUA2gBh1nG7MImIlHBt+xJ4aZKo91nPXGBBta4aAQUsHRkODG8dKb9tSZNsLBvt3kz5Fjg7srv1eiYr2yRa2ZCFKZ2rPAR69mVzLK55q+P1v6TE1hFL3Hf9Ijj+B+0cxmnc21qPdu0HFk=,iv:EzfgeA9Ze0tbMnDKwNh0sXSBbEGRF5xonz+FLNjqHDo=,tag:J/83i1DeABnKfVPmqy25cA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
