---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: botkube
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.botkube.io/
      chart: botkube
      version: v1.10.0
      sourceRef:
        kind: HelmRepository
        name: botkubeio-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    replicaCount: 1

    settings:
      clusterName: k8s-cluster
      configWatcher: true

    # -- Role Based Access for Botkube Pod and plugins.
    # [Ref doc](https://kubernetes.io/docs/admin/authorization/rbac/).
    rbac:
      groups:
        'botkube-plugins-default':
          create: true
          rules:
            - apiGroups: ["*"]
              resources: ["*"]
              verbs: ["get", "watch", "list"]

    communications:
      default-group:
        discord:
          enabled: true
          channels:
            default:
              notification:
                disabled: false
              bindings:
                executors:
                  - k8s-default-tools
                sources:
                  - k8s-recommendation-events
                  - k8s-all-events
                  - k8s-err-with-logs-events

          notification:
            type: short

    serviceMonitor:
      enabled: false

    actions:
      'describe-created-resource':
        enabled: false
      'show-logs-on-error':
        enabled: true

    sources:
      k8s-recommendation-events:
        botkube/kubernetes:
          enabled: true

      k8s-all-events:
        botkube/kubernetes:
          enabled: true
          resources:
            - type: v1/pods
            - type: v1/services
            - type: networking.k8s.io/v1/ingresses
            - type: v1/nodes
            - type: v1/namespaces
            - type: v1/configmaps
            - type: rbac.authorization.k8s.io/v1/roles
            - type: rbac.authorization.k8s.io/v1/rolebindings
            - type: rbac.authorization.k8s.io/v1/clusterrolebindings
            - type: rbac.authorization.k8s.io/v1/clusterroles
            - type: apps/v1/daemonsets
            - type: apps/v1/deployments
            - type: apps/v1/statefulsets

      k8s-err-with-logs-events:
        botkube/kubernetes:
          enabled: true

    executors:
      k8s-default-tools:
        botkube/kubectl:
          enabled: true

    aliases:
      k:
        command: kubectl
        displayName: "Kubectl alias"

      kgp:
        command: kubectl get pods
        displayName: "Get pods"

    resources:
      requests:
        cpu: 100m
        memory: 138Mi
      limits:
        memory: 1000Mi

    analytics:
      disable: true

  valuesFrom:
    - targetPath: communications.default-group.discord.token
      kind: Secret
      name: botkube-secrets
      valuesKey: BOTKUBE_DISCORD_TOKEN
    - targetPath: communications.default-group.discord.botID
      kind: Secret
      name: botkube-secrets
      valuesKey: BOTKUBE_DISCORD_BOT_ID
    - targetPath: communications.default-group.discord.channels.default.id
      kind: Secret
      name: botkube-secrets
      valuesKey: BOTKUBE_DISCORD_CHANNEL_ID
