apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-external-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mealie-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OPENAI_API_KEY: "{{ .OPENAI_KEY }}"
  dataFrom:
    - extract:
        key: mealie
