apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vrising-config-v1
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
