---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vrising
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    controller:
      replicas: 0
    image:
      repository: trueosiris/vrising
      tag: "1.9"
    nameOverride: vrising
    env:
      TZ: "Europe/London"
      GAMEPORT: 9876
      QUERYPORT: 9877
      SERVERNAME: ${VRISING_SERVER_NAME}
      VR_PASSWORD: ${VRISING_SERVER_PASSWORD}
      VR_MAX_USERS: 4
      VR_LIST_ON_MASTER_SERVER: false
    service:
      main:
        ports:
          http:
            port: 4000
      server:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${SVC_VRISING_ADDRESS}
        externalTrafficPolicy: Local
        ports:
          server:
            enabled: true
            port: 9876
            protocol: UDP
            targetPort: 9876
          query:
            enabled: true
            port: 9877
            protocol: UDP
            targetPort: 9877
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    resources:
      requests:
        memory: 2000Mi
        cpu: 100m
      limits:
        memory: 4000Mi
    persistence:
      config:
        enabled: true
        mountPath: /mnt/vrising/persistentdata
        existingClaim: vrising-config-v1
      server:
        enabled: true
        type: emptyDir
        mountPath: /mnt/vrising/server
    podAnnotations:
      secret.reloader.stakater.com/reload: "vrising"
