---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sonarr
  namespace: flux-system
spec:
  targetNamespace: media
  path: ./kubernetes/apps/media/sonarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  timeout: 5m
  dependsOn:
    - name: volsync
  postBuild:
    substitute:
      APP: *app
      CLAIM: *app
      VOLSYNC_CAPACITY: 1Gi
