---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app home-assistant
  namespace: flux-system
spec:
  targetNamespace: home
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/home/home-assistant/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: longhorn
    - name: volsync
    - name: multus
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      CLAIM: home-assistant-config
      VOLSYNC_CAPACITY: 2Gi
