---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname home-assistant
  namespace: flux-system
spec:
  targetNamespace: home
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  path: ./kubernetes/apps/home/home-assistant/app
  prune: false # revert
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: longhorn
    - name: volsync
    - name: multus
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *appname
      # APP_UID: "0"
      # APP_GID: "0"
      CLAIM: home-assistant-config
      VOLSYNC_CAPACITY: 2Gi
