---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: hass-homekit-static
  namespace: home
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "hass-homekit-static",

      "plugins": [
        {
          "type": "macvlan",
          "master": "bond0",
          "mode": "bridge",
          "capabilities": {
            "ips": true
          },
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "192.168.183.0/24", "gw": "192.168.183.1" }
            ]
          }
        },
        {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }
