---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  targetNamespace: observability
  path: ./kubernetes/apps/observability/grafana/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false # no flux ks dependents
  interval: 30m
  timeout: 5m
  dependsOn:
    - name: external-secrets-stores
    - name: ingress-nginx-internal
