apiVersion: v1
kind: Secret
metadata:
    namespace: monitoring
    name: botkube-communication
stringData:
    comm_config.yaml: ENC[AES256_GCM,data:OXjn+eBNdoaw4gf2dQf7cGhrJGFq573+41vKfmHnk82ipy3xwsvMbxRss+cF+qwLd39MDW4DXxpbszmYbq6oBRaHAhuonvpRWjZJx9YH89Wr3Rj0/xO4d+W/n5bRsaHJX6kINVT3Wyn/O8Rd7BIq47lK4Wx4URVyb0fl27abQ6Sppj0IsOUL9LiBmIy492VXS949wbsmWAq2fVpxJVqDk0PtvH9WqSzTjgWpaoS9i8S5ar/GS7Nc+z7ieZnzxXUKe09O+oCGna/Nt6bKl1URqsLMAdTwLEviLUjts8FSpvHm3LHSpzxM+wGlJ21zUnpWr12E+rXBy5SH0zJhHwNdrVXKmp9BEXQsqNq+OtYUf2KziSXyxCLyNINVbQNHeJeD5SbEpNAa8rNyxB78uvbs6zoh/2e6kQR3sjQPRDJEZHQ8+aCxaB9+huXSL+azBjTiOtjoB4KSno5C3bSICahEjn4988tU3Vo/KG2+MnCwi/1g+k0X5GoPtrOXwrKwFApbNc0In4KVr7zEQGhBbW4qY9gDn0/bG86ybHYurJBCivYk6C9xmkoK1Pf5wGXf/FiPyHhnTchRTyYXyjx/8FT/Prsq0UCUCrZ1s8iZMURug69bJsJocz6YL6Rgn3VUjgZWw0HZocxUyRgeaUn06+eUFPcJlEKHxnEEu+G1EXJnSIQ8p7+qeCzM3zEuulQEHgv2U/u748xW/ieXAolKN06V9lHuG885CVLBgP/5Ep2wGkp8u5C8RQtu,iv:L+Vs8YUfk7GqPUl4RTG23XWMYPLDg7YwGfOj1QUw/zE=,tag:YgB5hS3fXA5hdqcZDLeqQw==,type:str]
##  stringData:
##    comm_config.yaml: |
# as a string
# communications:
#   'default-group':
#     discord:
#       enabled: false
#       token: 'DISCORD_TOKEN'
#       botID: 'DISCORD_BOT_ID'
#       channels:
#         'default':
#           id: 'DISCORD_CHANNEL_ID'
#           notification:
#             # -- If true, the notifications are not sent to the channel. They can be enabled with `@Botkube` command anytime.
#             disabled: false
#           bindings:
#             executors:
#               - kubectl-read-only
#             sources:
#               - k8s-err-events
#               - k8s-recommendation-events
#       notification:
#         # -- Configures notification type that are sent. Possible values: `short`, `long`.
#         type: short
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMDBkUEM0QXo0b2RvNUNY
            U3UwUTNUMlAxem11Mld0TVg1NWtSUlM5V3lFCllDbzI0Z1JZNnZaNENCQytpQ29S
            eWNNVEpRQ3liZDZnWUVtQzJ4KytwSVUKLS0tIHNPamNleVV1U2FSVXVRMmpHcEth
            WlZoSkZIbDdEU285Nkk1TitSelR5RXMKgTsVRtslqk9vh+CskfeS4j2DYX+vaHAn
            c2EytbnxlkRQk15PWcddmQjOJ2spfzPcWNlWSW4XSMtDYu5v9Uqwsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-02T13:19:08Z"
    mac: ENC[AES256_GCM,data:ohASfHBuCwsnKTX7FCOgVGtBa39gy6+1pMbEegKMfXVVko9hzayD2hVJ9aqpU6e71+HbJ6w18dtBOLFOVx4y6JwbQFiAJqTe9gjoceqPDhmveMj3opLDKIJAZL6HBwHz2LfZ6REg5Ez3aA+4UcsA6s0U/JLEht7ZTjgF543jhY8=,iv:YFeaEny5zEK2ukLzRgWs9U0AmpWmL/TOhP4KJCZpIAQ=,tag:IdPq1vGbS84bT52EdtZk/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
