apiVersion: v1
kind: Secret
metadata:
    namespace: monitoring
    name: botkube-communication
stringData:
    comm_config.yaml: ENC[AES256_GCM,data:m8fS3WNSzceNPwj46aJMmO6/H9trhOizKhixPwyzik3U/9Y0dMmpnrh2vBbEbbxsqvjTHYj5mB+2646284UmGFCDuOnB0UgjoRk+FuTVqD6cO2aTqjtmIrQKej/gCifKHBUZUA6HxJD3waWulXd8wqsLoVg66VYI3cpt+uidOdNjgXcsjk1s6KnIkxiXhFZuJZGGPS8ORrKPp4+aEUuTUPYIkAQD2mF6DYtAjC48pv23JnGSyBTWAk/BXeYvrORSszMcl/PeaTN4xqV+rSdxu2gCA/fjyeA8gIbOWXXSPdtlzTkRGOpRMJUwY0GYYUhH94OMkYtzCw6KH4q076l3dnPtQGYhrVpe1GtGpFrthKHwZTlmy1aIEIwjDlU1xjFUdsb+PxKU+J1DCX8R2Jz2P05MJHmXXcqeeVDMIbQZHJS5FlZBVRAJbGaXmO5PyZuQtiVjb0mDu1xou6rDl3UDZHuGQbA8We4rYmrDJWn5emztYPN3l9apF4HePYVJKZ4A0pBLfrrxl5tjP1qgy84t6CHHaosv6GBtqO/R8yR19ZFrH2223UdNdLqO7AgoMOkqC/9BAiHUVy+uvDsdWkETcmie0je58kGOs9tSKyt9+oEC4w1abpwkn6QGk+0nSRjoWXVbi/43c+5/5UOEFpIACEhDRkisoYjGg9UZWphghYuuhKByYWKxOvPlvWKUIBacdT4oeTig8kroI3yC6t53q0rBC0VvI/Nsc8jzd359zcqdkQXkY9LSqXgA4RHi0C8+VORMJyezqdsvQCD02auE5EqajW48cHlkDa7mEV8XwNzbyBFKLbn0BsZArmLvn4Z1WS8aYxcs0M7V/UGmqGo=,iv:8XmvL5j6zgzjmUombpM2xiTR0yYqprWB6JGXLWpBJeg=,tag:05vnhr/tfvyAAMnxx6i05w==,type:str]
##  stringData:
##    comm_config.yaml: |
# as a string
# communications:
#   'default-group':
#     discord:
#       enabled: false
#       token: 'DISCORD_TOKEN'
#       botID: 'DISCORD_BOT_ID'
#       channels:
#         'default':
#           id: 'DISCORD_CHANNEL_ID'
#           notification:
#             # -- If true, the notifications are not sent to the channel. They can be enabled with `@Botkube` command anytime.
#             disabled: false
#           bindings:
#             executors:
#               - kubectl-read-only
#             sources:
#               - k8s-err-events
#               - k8s-recommendation-events
#       notification:
#         # -- Configures notification type that are sent. Possible values: `short`, `long`.
#         type: short
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v9n8sg6r85f5yd84yg5q9ssth0mz6ujtjjtk664mseej0fr2jf6s8l9umt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMDBkUEM0QXo0b2RvNUNY
            U3UwUTNUMlAxem11Mld0TVg1NWtSUlM5V3lFCllDbzI0Z1JZNnZaNENCQytpQ29S
            eWNNVEpRQ3liZDZnWUVtQzJ4KytwSVUKLS0tIHNPamNleVV1U2FSVXVRMmpHcEth
            WlZoSkZIbDdEU285Nkk1TitSelR5RXMKgTsVRtslqk9vh+CskfeS4j2DYX+vaHAn
            c2EytbnxlkRQk15PWcddmQjOJ2spfzPcWNlWSW4XSMtDYu5v9Uqwsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-02T13:15:43Z"
    mac: ENC[AES256_GCM,data:r3qiSnKbc1vQuggQrzeqtZLpp3o6p93UaJ5oyqikTd1gxZrlZPvys/9qku0Ka1SVIKFuK7O30o8zgxxzPGWLVHhUWQg2hkoIMs4nOpIFmmcnasw2F8dEPyOKKrR8LoGggM5EOvf1HZlVJGwKMAUKUXBteBdTE06IP9Qcl8Gpjzo=,iv:SiH2uv1nBkrhvI/f/uf1KvqMXZYl6xBnHqKvaCHTM9I=,tag:Tqo4qLmiSgBlrj5d98RBRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
