---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.fairwinds.com/stable
      chart: goldilocks
      version: 8.0.2
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
      interval: 5m
  values:
    vpa:
      enabled: true
    dashboard:
      enabled: true
      replicaCount: 1
      flags:
        enable-cost: "false"
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/appName: "goldilocks"
          hajimari.io/icon: "abacus"
          hajimari.io/group: "monitoring"
        hosts:
          - host: &host "goldilocks.${SECRET_DOMAIN}"
            paths:
              - path: /
                type: Prefix
        tls:
          - hosts:
              - *host
