---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app plex
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  targetNamespace: media
  path: ./kubernetes/apps/media/plex/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  timeout: 5m
  dependsOn:
    - name: volsync
    - name: ingress-nginx-internal
    - name: longhorn

  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 30Gi
      VOLSYNC_CLAIM: plex-config
